%{
Script for plotting the OSA Spectra for the VFN Polychromatic Paper

This script loads all the VFN spectra in a given directory and plots them, 
overlayed, on a single axis. Input files should be .mat generated by the OSA. 

NOTE: this script was originally run on the VFN Server (Ubuntu).

Author:         Daniel Echeverri
Origin Date:    07/24/2021
%}

close all; clear all;

mW2uW = 1e3;    % mW to uW conversion since OSA data comes in mW
%% User Inputs

%-- Folder with the spectra files
fld = '/media/Data_Drive/VFN/OSA_Meas/210720_VariaForPolyPaper/ThirdSet_AsUsedForPolyPaperData';

%-- Save Information
% Folder into which figure should be saved
savefld = '/media/Data_Drive/VFN/TestbedData_Processed/PolyPaper';
% Filename for saved figure
flnm    = 'VFN_PolyPaper_VariaSpectra';
% Filetype for saved figure
fltype  = '.png';
% Flag to decide if figure should be saved
isSave  = true;

%-- Figure properties
% Fontsizes are in 'normalized' units. That means the value should be
  % fractional [0 to 1]. Ex: 0.1 sets text to 10% of the figure height.
fontsize1 = 0.07;         % Fontsize for big text 
fontsize2 = 0.05;         % Fontsize for smaller text
linewidth = 1;          % Linewidth for plot lines
x_lims    = [600, 700]; % limits for x-axis (leave [] to use default)
y_lims    = [0,2.2];    % limits for y-axis (leave [] to use default)
figdim    = [8, 6];     % [width, height] in inches for the figure

%% Load the data
%-- Find all .mat files in the given directory
flnms = dir(fullfile(fld, '*.mat'));

%-- Preallocate the data matrices
% Assume that all spectra will have the same number of elements. Thus use
% the size of the first set 
data = load(fullfile(flnms(1).folder,flnms(1).name));
wvs  = nan(length(flnms),length(data.wavelength_nmAir));
spec = nan(length(flnms),length(data.spectrum));

% Iterate through files loading them
for ind = 1:length(flnms)
    data = load(fullfile(flnms(ind).folder,flnms(ind).name));
    wvs(ind,:)  = data.wavelength_nmAir;
    spec(ind,:) = data.spectrum;
end

%% Display the data
fig = figure('color','white','units', 'inches', 'Position', [0 0 figdim]);
% NOTE: transpose when plotting is needed to get the right matrix orientation
plot(wvs',spec'*mW2uW, 'LineWidth',linewidth);  
if ~isempty(x_lims)
    xlim(x_lims)
end
if ~isempty(y_lims)
    ylim(y_lims)
end
grid on; grid minor;
xlabel('Wavelength [nm_{air}]')
ylabel({'Spectrum [\muW]',' '})
title({'Varia Spectra for VFN Tests',' '})
set(gca, 'FontUnits', 'normalized', 'fontsize', fontsize2)

%% Save the figure
if isSave
    flnm_svd = fullfile(savefld,[flnm fltype]);
    export_fig(fig,flnm_svd,'-r300', '-painters');
    fprintf('\nFigure saved to:\n  %s\n',flnm_svd)
end